name = "Skrimpie+ Modpack"
author = "Skrimp"
version = "26.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1ea148e1bd5846dd8120d8176e0e00ce9f22e72e94b391566dbcd79b515ef81"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
